version: '3.9'
services:
  app:
    image: ghcr.io/algostract/jellyfish-bowl:latest
    env_file:
      - .env.prod
    ports:
      - 4310:3000
    networks:
      - front-tier
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3

  typesense:
    image: typesense/typesense:28.0
    command: --data-dir /data
    env_file:
      - .env.prod
    volumes:
      - search-data:/data
    networks:
      - front-tier
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3

networks:
  front-tier:
    driver: overlay

volumes:
  search-data:
