version: '3.9'
services:
  app:
    image: ghcr.io/algostract/red-cat-muse:latest
    env_file:
      - .env.prod
    ports:
      - 4310:3000
    networks:
      - front-tier
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        max_attempts: 3

  typesense:
    image: typesense/typesense:28.0
    command: --data-dir /data --api-key=${TYPESENSE_API_KEY}
    env_file:
      - .env.prod
    volumes:
      - search-db-data:/data
    ports:
      - 8108:8108
    networks:
      - front-tier

networks:
  front-tier:
    driver: overlay
