name: 'gold-fish-bowl-dev'
services:
  app:
    build: .
    restart: on-failure:3
    env_file:
      - .env.prod
    ports:
      - 4310:3000

  typesense:
    image: typesense/typesense:29.0
    command: --data-dir /data
    env_file:
      - .env.prod
    volumes:
      - search-data:/data
    ports:
      - 8108:8108

volumes:
  search-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./.data
