name: 'red-cat-muse-dev'
services:
  app:
    build: .
    restart: on-failure:3
    env_file:
      - .env.prod
    ports:
      - 4310:3000

  typesense:
    image: typesense/typesense:28.0
    command: --data-dir /data --api-key=${TYPESENSE_API_KEY}
    env_file:
      - .env.prod
    volumes:
      - search-db-data:/data

volumes:
  search-db-data:
