version: '3.9'
services:
  app:
    image: 'ghcr.io/algostract/red-cat-muse:latest'
    env_file:
      - .env.prod
    ports:
      - 4310:3000
    networks:
      - front-tier
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        max_attempts: 3

networks:
  front-tier:
    driver: overlay
